### ISSUE TITLE
can not draw the waveform on the  new version vscode

### ISSUE THREAD

**Issue by Hea-john-09** [bmpenuelas/waveform-render-vscode#15]

**Comment by Nabav** [comment]
Also for me with v0.19.0 and VSCode 1.73.0 on Linux.

**Comment by Hea-john-09** [comment]
> Also for me with v0.19.0 and VSCode 1.73.0 on Linux.

I had fix it by changing the extension.js
![image](https://user-images.githubusercontent.com/68043817/200263926-da8cb16b-079b-44ff-aeaf-174b5594b94e.png)

**Comment by Nabav** [comment]
@bmpenuelas, can you please consider this in a release?

**Comment by bmpenuelas** [comment]
Of course @Nabav ! I will push an update asap. 

Thank you @Hea-john-09 for the heads up!

**Comment by bmpenuelas** [comment]
New release has been published to the marketplace!
