### ISSUE TITLE
Feature request: please support wavedrompy for wavedrom in python

### ISSUE THREAD

**Issue by bedo1337** [bmpenuelas/waveform-render-vscode#18]
wavedrom in python (wavedrompy) is easier to install on some systems than original wavedrom that requires node.js

https://pypi.org/project/wavedrom/

you can render waves using command

`wavedrompy --input input.json --svg output.svg`

**Comment by bmpenuelas** [comment]
Hi, this repo is for Wavedrom in VSCode. You just have to install the extension inside VSCode, and nothing else. What is your request exactly about?
