### ISSUE TITLE
Feature request: support popping out into new windows

### ISSUE THREAD

**Issue by DeflateAwning** [bmpenuelas/waveform-render-vscode#19]
VSCode just recently (within the last 3 months) added the ability to have multiple windows in a single workspace. However, when you try to drag a Wavedrop Preview tab into a new window, it gives an error message: "This type of editor cannot be opened in other windows yet.", and only shows the option to "Close Editor".

It's possible it's not supported at all in VSCode yet. Would be awesome if this was possible though.

### Temporary Workaround for now
You can drag the JSON editor to a new window, and keep the preview in its original space, and it continues to work fine.

**Comment by bmpenuelas** [comment]
Hi, I have just tested this with the latest version (VSCode 1.88.1 , extension v0.23.0) and it seems to be working correctly.

Here's how I tested it:
- Open a json with wavedrom data
- Turn on live preview from the command palette
- New tab appears displaying the waveform
- Right click the waveform tab -> Move into New Window
- Type some new changes in the original JSON file tab, the wave which is in a separate window now updates correctly

Can you please give it a try and let me know if it works well for you too?

**Comment by DeflateAwning** [comment]
Works for me as well! Those were the steps I was doing in the first place.

Not sure if a recent update fixed this, or if VS Code implemented something that made this work by default, but very awesome!

You can close this issue!

**Comment by bmpenuelas** [comment]
Happy to hear that, closing then!
