### ISSUE TITLE
Editor tab should preserve focus after draw

### ISSUE THREAD

**Issue by Nabav** [bmpenuelas/waveform-render-vscode#2]
Thanks for the great extension.

It would be great if the focus is not transferred to the preview tab after each time user invokes the `draw` command. This will lead to a very fluid (edit, preview, evaluate changes) work cycle just inside the editor tab.

**Comment by bmpenuelas** [comment]
Totally agree! Said and done, it's available now in commit https://github.com/bmpenuelas/waveform-render-vscode/commit/d076de86bc605d71d27a4703549284ea4b9986f6 :smile:
