### ISSUE TITLE
Wave can't be export by prince （from .md to .pdf）

### ISSUE THREAD

**Issue by hankonly** [bmpenuelas/waveform-render-vscode#21]
i just want a tool to export *.md to a *.dpf
1) when i used chrome, it can export the wave, but the .pdf has no bookmarker
2) so i chosed 'prince' as the tool (from .md to .pdf), but the wave is lost.

**Comment by bmpenuelas** [comment]
Hello, wavedrom exports SVG. Converting to .pdf is outside of the scope of this extension, you can export the SVG and convert that file using a different tool of your choice.

**Comment by hankonly** [comment]
thanks for your rsp.
