### ISSUE TITLE
Toggling on Live Render doesn't update until you start typing

### ISSUE THREAD

**Issue by DeflateAwning** [bmpenuelas/waveform-render-vscode#24]
This is a very very minor issue, but figured I could still type it out.

### Steps to Reproduce

1. Open JSON wavedrom file.
2. Turn on "Draw" with command palette
3. Make a change in the JSON file, and save the JSON file.
4. Turn on "Live Preview" with command palette
5. See that the preview still shows the version from Step 1, and does not reflect the change in Step 3.

I believe that by turning on Live Preview, you are saying that you want it to match what's currently in the file, and what gets update thereafter (i.e., in Step 3).

**Comment by bmpenuelas** [comment]
Thanks for the input. I agree so I've fixed it and released a new version, please let me know if it works as expected now.

**Comment by DeflateAwning** [comment]
Looks good to me!
