### ISSUE TITLE
Update to latest version of WaveDrom

### ISSUE THREAD

**Issue by mrvkino** [bmpenuelas/waveform-render-vscode#4]
There is a more recent version of wavedrom from less than a month ago.

https://github.com/wavedrom/wavedrom/releases

**Comment by bmpenuelas** [comment]
Thanks for the heads-up! Now it's updated to the latest version (https://github.com/bmpenuelas/waveform-render-vscode/commit/ed5faceabb8ddcf2ce9339240954ed36f8e2164d).
