### ISSUE TITLE
Drawing difference with online waveform editor

### ISSUE THREAD

**Issue by mrvkino** [bmpenuelas/waveform-render-vscode#5]
When I run the following code:
```
{reg:[
    {bits: 7,  name: 0x07, attr: [
      'VLxU,VLE zero-extended',
      'VLxU,VLE zero-extended, fault-only-first',
      'VLxU sign-extended',
      'VLxU sign-extended, fault-only-first',
    ]},
    {bits: 5,  name: 'vd', attr: 'destination of load', type: 2},
    {bits: 3,  name: 'width'},
    {bits: 5,  name: 'rs1', attr: 'base address', type: 4},
    {bits: 5,  name: 'lumop', attr: [0, 16, 0, 16]},
    {bits: 1,  name: 'vm'},
    {bits: 3,  name: 'mop', attr: [0, 0, 4, 4]},
    {bits: 3,  name: 'nf'},
]}
```

I get a different result from the online editor of wavedrom. The register is on two line instead of one.

![wavedrom](https://user-images.githubusercontent.com/279511/59871056-ac67b080-9364-11e9-85a5-e399d18fb163.png)
compared to [this](https://wavedrom.com/editor.html).

Thanks for the extension. I love it.

**Comment by bmpenuelas** [comment]
Hi, I have just checked and found out that there were two files with different dates. The updated version is live now in the marketplace, please update in vscode and check if it works as expected now.

**Comment by mrvkino** [comment]
Yup! I have the same results.

Thanks for the fix.

**Comment by bmpenuelas** [comment]
Any time :smile:
