### ISSUE TITLE
[Feature-Request] Save preview as image file (png/svg)

### ISSUE THREAD

**Issue by joshrsmith** [bmpenuelas/waveform-render-vscode#6]
Would it be possible to allow saving the preview image as a PNG/SVG? The wavedrom native editor supports this, but not from what I can tell in VS Code.

Someone who wants to save as PNG now must screen shot, or paste it back in the original wavedrom editor. If there is another way I am not thinking of let me know.

**Comment by bmpenuelas** [comment]
Hi, PNG rendering (and saving) is done by the engine. Web browsers do it all right, but unfortunately VSCode doesn't. 

Save as SVG, on the other hand, works correctly (right-click on the waveform).

**Comment by joshrsmith** [comment]
Ok, thanks for the tip.
Thanks for the useful extension!

**Comment by bmpenuelas** [comment]
Np, I will reopen this if it's possible to do it in the future.
