### ISSUE TITLE
Support More Colors

### ISSUE THREAD

**Issue by Nabav** [bmpenuelas/waveform-render-vscode#7]
The latest version of Wavedrom renders 4 new colors announced [here](https://github.com/wavedrom/wavedrom/issues/150#issuecomment-559352374).

It would be great to have this (and probably other) new feature(s) in VSCode as well.

**Comment by bmpenuelas** [comment]
Thanks! Updated to latest in https://github.com/bmpenuelas/waveform-render-vscode/commit/2fe3815f691affb6acbeeb8793977cd1be4b30af , can you check?

**Comment by Nabav** [comment]
I have checked and I have all new colors. Thanks for the quick support.
