### ISSUE TITLE
[Feature Request] Link with source json file (live preview)

### ISSUE THREAD

**Issue by obiwanjacobi** [bmpenuelas/waveform-render-vscode#9]
First, thanks for creating this extension.

Currently (0.18.0) the preview re-renders on changes on the current document, even if that document is not a wavedrom json file.
It would be nice if the preview would maintain a link to the source json file it is rendering and only redraw on those changes. It would also allow multiple preview instances to different source files.

**Comment by bmpenuelas** [comment]
Hi! Thanks a lot for the request, it definitely makes the experience better. I have implemented it in 9026ceb , the new release is already in the marketplace 😄
